### ISSUE TITLE
Wording re: "false positives"

### ISSUE THREAD

**Issue by ccronje** [data-lessons/library-shell#21]
A suggestion for [this episode](https://github.com/ccronje/library-shell/blob/gh-pages/_episodes/01-intro-shell.md) - change:

> There are a few false positives, but this is still a good start: from 500,000 lines of journal article metadata to a few numbers and names just by typing one line of code.

to 

> There are a few false positives (e.g. the string was found in the Publisher field and grep returns the whole line), but this is still a good start: from 500,000 lines of journal article metadata to a few numbers and names just by typing one line of code.

**Comment by drjwbaker** [comment]
For me returning the whole line is what we are trying to achieve! with tabular data! The false positives are places were `INTERNATIONAL` isn't in the journal column (I don't specify a column in the opening bit because I'm trying to get across the idea that your code doesn't need to be perfect, that in the first instance is better sometimes to get a sense of the output before refining it)

**Comment by ccronje** [comment]
Yes, ok let's keep the wording as is.
