### ISSUE TITLE
Setup is not clear enough

### ISSUE THREAD

**Issue by saschel** [data-lessons/library-shell#41]
For non technical persons, it's not clear what they should do i.e.  'open a terminal'

**Comment by jt14den** [comment]
I agree! The setup file was copied verbatim over from https://swcarpentry.github.io/shell-novice/setup/.  Maybe we can adapt something from Data Carpentry http://www.datacarpentry.org/shell-genomics/lessons/01_the_filesystem.html#how-to-access-the-shell? @saschel would you be willing to come up with some language or a pull request for this?

**Comment by drjwbaker** [comment]
Further to @jt14den and @weaverbel, this lesson appears to have lost all reference to Windows users needing to install Git Bash. Shouldn't this be here http://data-lessons.github.io/library-shell/setup/ ?

**Comment by evanwill** [comment]
Software Carpentry has the setup done separately from the lesson, with the idea that participants do setup once before the 2 day workshop. So rather than having the setup steps in the lesson, they are in the [workshop-template](https://github.com/swcarpentry/workshop-template) repository, which creates a website for a specific SWC 2 day workshop, like http://swcarpentry.github.io/workshop-template/

Thus, SWC lessons assume that everyone already has a proper UNIX shell set up with Nano, SQLite, Git, and Python or R. They have been using the [Windows Installer](https://github.com/swcarpentry/windows-installer) to automate getting windows set up with the shell. However, it's been a big discussion about changing the installer, since it's out of date and difficult to maintain.

Anyway, that is why there is a missing step when you copy "setup" from individual SWC lessons, like https://swcarpentry.github.io/shell-novice/setup/

**Comment by evanwill** [comment]
There is a few discussions about how to handle windows set up ([here](https://github.com/carpentries/conversations/issues/11)), and people have tried a few alternatives the Git Bash or the SWC Windows Installer:

[Cmder](http://cmder.net/) (complete install comes with Git Bash, but is fully portable, so you could configure it in advance and have everyone download your copy)

[Cygwin](https://github.com/swcarpentry/workshop-template/pull/391)

[Conda](https://github.com/swcarpentry/workshop-template/issues/395) (handy if you are teaching Python, otherwise not)

**Comment by drjwbaker** [comment]
Thanks @evanwill. My memory is that we lost this in the sprint, but haven't moved fully to a generic pre-workshop setup doc to accommodate. For consistency with the Refine lesson http://data-lessons.github.io/library-openrefine/ I feel we should have the install here. Maintainers, could you take a look please?

**Comment by evanwill** [comment]
Maybe the setup notes you are thinking of are the ones at the end of the [guide.md](https://github.com/data-lessons/library-shell/blob/gh-pages/_extras/guide.md) in this lesson?

**Comment by evanwill** [comment]
I am making a PR #51 that I think addresses this issue.

**Comment by msarahan** [comment]
@evanwill this comment is far too late to be useful, but I wanted to point out that conda is not strictly for Python.  It is historically Python-centric, but you can install R, perl, low-level system depednencies, and pretty much anything else with conda, too.  On windows, conda provides several MSYS2 packages that make life better, such as mintty.  It is much closer to cygwin than it is a "python distribution"
